# syntax=docker/dockerfile:1

FROM cgr.dev/chainguard/python:latest-dev as dev

LABEL org.opencontainers.image.authors="jorgedonato@gmail.com"

#ENV PATH="/home/nonroot/.local/lib/python3.14/site-packages/bin:/home/nonroot/.local/bin":$PATH

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --user --no-cache-dir -r requirements.txt

FROM cgr.dev/chainguard/python:latest

WORKDIR /app

#ENV PATH="/home/nonroot/.local/lib/python3.14/site-packages/bin:/home/nonroot/.local/bin:$PATH"

COPY --chown=nonroot:nonroot app.py .
COPY --chown=nonroot:nonroot templates templates/
COPY --chown=nonroot:nonroot static static/
ENV REDIS_HOST="192.168.15.60"
COPY --from=dev --chown=nonroot:nonroot /home/nonroot/.local/lib/python3.14/site-packages /home/nonroot/.local/lib/python3.14/site-packages
COPY --from=dev --chown=nonroot:nonroot /home/nonroot/.local/bin/flask /app/flask
#RUN ln -s /home/nonroot/.local/bin/flask /app/flask

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]