apiVersion: policies.kyverno.io/v1
kind: DeletingPolicy
metadata:
  name: cleanup-empty-replicasets
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["replicasets"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
  conditions:
    - name: is-empty
      expression: "object.spec.replicas == 0"
  schedule: "* * * * *"