apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 9113
    targetPort: 9113
    protocol: TCP
    name: metrics
  type: ClusterIP