apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: app-nginx
spec:
  replicas: 10
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      app: nginx-deploy
  strategy: 
    # type: Recreate
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.3"
            memory: "256Mi"

