apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: redis
        ports:
          - containerPort: 6379
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts: # lista de volumes que serão montados no container
        - name: redis-data # nome do volume
          mountPath: /data # diretório onde o volume será montado
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: meu-pvc